### ISSUE TITLE
Not utilizing original generator/discriminator in combined model

### ISSUE THREAD

**Issue by alvin-wu** [wayaai/GAN-Sandbox#2]
Line 145 in master branch
Line 168-169 in cGAN branch
Line 154 in ac-gan branch
Line 160 in info-gan

**Comment by mjdietzx** [comment]
Thank you for catching this!

Fixed: 2130ef4397a93354fbf378a302e84c97c1b52dd9

**Comment by mjdietzx** [comment]
Fixed in all branches I think
